# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://www.bissoy.com/q/1111111262187")
    self.driver.set_window_size(852, 738)
    assert self.driver.find_element(By.CSS_SELECTOR, ".qa-who span").text == "HassanJubaa"
    assert self.driver.find_element(By.CSS_SELECTOR, "#a-1111111262782 .qa-user-link > span").text == "সোহাগহাসান"
    self.driver.find_element(By.CSS_SELECTOR, "#a-1111111262782 p").click()
    self.driver.execute_script("window.scrollTo(0,939)")
    assert self.driver.find_element(By.CSS_SELECTOR, "#a-1111111262782 p").text == "দাড়ি প্রাকৃতিক একটি বিষয় এটা প্রাকৃতিকভাবেই গজাবে....তবে বাজারে কিছু ব্রেড ওয়েল পাওয়া যায় ঐগুলো চেস্টা করতে পারেন....!!"
    self.driver.find_element(By.CSS_SELECTOR, "#a-1111111262782 p").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#a-1111111262784 .qa-user-link > span").text == "Jamiar"
    self.driver.find_element(By.CSS_SELECTOR, "#a-1111111262784 .answer").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".answer > p:nth-child(3)").text == "তাই বলা সম্ভব না ও উপায় নেই নিজ থেকেে  চাপ দাড়ি গজানো।"
    self.driver.find_element(By.CSS_SELECTOR, ".answer > p:nth-child(3)").click()
  
